#!/bin/sh

VENUSDIR=/home/a/arnab/aggregator/venus
OUTDIR=/home/a/arnab/abhatt.github.io

[ -d ${VENUSDIR} ] || exit 0;

cd $VENUSDIR
for i in config/*.ini; do
        python planet.py $i 2> /tmp/planet-error.log
#        python comments.py $i 2> /tmp/planet-comments-error.log
done;

python reformatfeed.py < $OUTDIR/atom.xml > $OUTDIR/atom-twitter.xml 2> /tmp/planet-reformat-error.log

cd $OUTDIR
git commit index.html atom.xml atom-twitter.xml -m "Hourly Updates"
git push origin master
